'use client';
import React from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Skills from './@skills/page';
import History from './@history/page';
import Profile from './@profile/page';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  skills,
  history,
}: {
  children: React.ReactNode;
  skills: React.ReactNode;
  history: React.ReactNode;
}) {
  const props = {
    children,
    skills,
    history,
  };
  const queryClient = new QueryClient();
  return (
    <html>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
        ></link>
      </head>
      <body>
        <QueryClientProvider client={queryClient}>
          <ReactQueryDevtools initialIsOpen={false} />
          <section className="py-4">{children}</section>
          <section className="py-6">
            <Profile />
          </section>
          <section className="flex gap-6">
            <Skills />
            <History />
          </section>
        </QueryClientProvider>
      </body>
    </html>
  );
}
